name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    # - name: Run tests
    #   run: cargo test --verbose
  
  test:
    runs-on: ubuntu-latest

    needs: build
    if: success() || failure()
    
    steps:
    - uses: actions/checkout@v3
    - name: Test Lexer
      run: cargo test lexer --verbose
    - name: Test Parser
      run: cargo test parser --verbose
    - name: Test All
      run: cargo test --verbose
